name: lint

on: push

jobs:
  python-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install pycodestyle
      - name: Run pycodestyle
        run: |
          pycodestyle .
